/** Translations of the English originals for languages our country list uses. */
export const EXTRA_TERMS: Record<string, Record<string, string[]>> = {
  gaming: {
    is: ["leikjamyndband", "let's play"],
    lv: ["spēļu video", "let's play"],
    lt: ["žaidimų video", "let's play"],
    el: ["gameplay", "παιχνίδι"],
    cs: ["gameplay", "hraní her"],
    hu: ["gameplay", "játékvideó"],
    ro: ["gameplay", "să jucăm"],
    uk: ["геймплей", "летс плей"],
    id: ["gameplay", "main game"],
    hi: ["गेमप्ले", "लेट्स प्ले"],
    ar: ["جيم بلاي", "لنلعب"],
    fil: ["gameplay", "maglaro"],
  },
  "pc-building": {
    is: ["smiða tölvu", "leikjatölva"],
    lv: ["salikt datoru", "spēļu dators"],
    lt: ["surinkti kompiuterį", "žaidimų PC"],
    el: ["χτίσιμο PC", "gaming PC"],
    cs: ["sestavení PC", "herní PC"],
    hu: ["PC építés", "gamer gép"],
    ro: ["asamblare PC", "PC gaming"],
    uk: ["збірка ПК", "ігровий ПК"],
    id: ["rakit PC", "PC gaming"],
    hi: ["पीसी बिल्ड", "गेमिंग पीसी"],
    ar: ["تجميع كمبيوتر", "كمبيوتر ألعاب"],
    fil: ["mag-build ng PC", "gaming PC"],
  },
  "budget-second-hand": {
    is: ["ódýr leikjatölva", "notað grafikkort"],
    lv: ["lēts spēļu dators", "lietota video karte"],
    lt: ["pigus žaidimų PC", "naudota vaizdo plokštė"],
    el: ["φθηνό gaming PC", "μεταχειρισμένη GPU"],
    cs: ["levné herní PC", "použitá grafika"],
    hu: ["olcsó gamer PC", "használt VGA"],
    ro: ["PC gaming ieftin", "GPU second hand"],
    uk: ["дешевий ігровий ПК", "б/у відеокарта"],
    id: ["PC gaming murah", "GPU bekas"],
    hi: ["सस्ता गेमिंग पीसी", "पुरानी GPU"],
    ar: ["كمبيوتر ألعاب رخيص", "كرت شاشة مستعمل"],
    fil: ["murang gaming PC", "second-hand GPU"],
  },
  "tech-reviews": {
    is: ["tæknidómur", "grafikkort próf"],
    lv: ["tehnikas apskats", "GPU tests"],
    lt: ["technikos apžvalga", "GPU testas"],
    el: ["tech review", "δοκιμή GPU"],
    cs: ["recenze techniky", "test GPU"],
    hu: ["tech teszt", "VGA teszt"],
    ro: ["review tech", "test GPU"],
    uk: ["огляд техніки", "тест відеокарти"],
    id: ["review teknologi", "review GPU"],
    hi: ["टेक रिव्यू", "GPU रिव्यू"],
    ar: ["مراجعة تقنية", "مراجعة كرت الشاشة"],
    fil: ["tech review", "GPU review"],
  },
  sustainability: {
    is: ["endurvætt tækni", "gera við"],
    lv: ["atjaunota elektronika", "remontēt"],
    lt: ["atnaujinta elektronika", "remontuoti"],
    el: ["ανακατασκευασμένα", "επισκευή"],
    cs: ["refurbished elektronika", "opravit"],
    hu: ["felújított elektronika", "javítsd"],
    ro: ["electronice recondiționate", "repară"],
    uk: ["відновлена електроніка", "ремонтуй"],
    id: ["elektronik refurbished", "perbaiki"],
    hi: ["refurbished इलेक्ट्रॉनिक्स", "मरम्मत"],
    ar: ["إلكترونيات مجددة", "أصلح لا ترمِ"],
    fil: ["refurbished electronics", "ayusin huwag palitan"],
  },
  beauty: {
    is: ["förðunartutorial", "húðvörur"],
    lv: ["grima tutorial", "ādas kopšana"],
    lt: ["makiažo tutorial", "odos priežiūra"],
    el: ["μακιγιάζ tutorial", "περιποίηση δέρματος"],
    cs: ["makeup tutoriál", "péče o pleť"],
    hu: ["smink tutorial", "skincare"],
    ro: ["tutorial machiaj", "îngrijire ten"],
    uk: ["макіяж туторіал", "догляд за шкірою"],
    id: ["tutorial makeup", "skincare"],
    hi: ["मेकअप ट्यूटोरियल", "स्किनकेयर"],
    ar: ["مكياج توتوريال", "العناية بالبشرة"],
    fil: ["makeup tutorial", "skincare"],
  },
  fitness: {
    is: ["heimæfing", "ræktin"],
    lv: ["mājas treniņš", "sporta zāle"],
    lt: ["treniruotė namie", "sporto salė"],
    el: ["προπόνηση σπίτι", "γυμναστήριο"],
    cs: ["cvičení doma", "posilovna"],
    hu: ["otthoni edzés", "edzőterem"],
    ro: ["antrenament acasă", "sală"],
    uk: ["тренування вдома", "зал"],
    id: ["olahraga di rumah", "gym"],
    hi: ["घर पर वर्कआउट", "जिम"],
    ar: ["تمرين منزلي", "نادي رياضي"],
    fil: ["home workout", "gym"],
  },
  food: {
    is: ["einföld uppskrift", "heimamatúr"],
    lv: ["viena recepte", "mājas ēst"],
    lt: ["paprastas receptas", "naminis maistas"],
    el: ["εύκολη συνταγή", "σπιτικό φαγητό"],
    cs: ["snadný recept", "domácí vaření"],
    hu: ["egyszerű recept", "otthoni főzés"],
    ro: ["rețetă ușoară", "gătit acasă"],
    uk: ["простий рецепт", "домашня їжа"],
    id: ["resep mudah", "masakan rumahan"],
    hi: ["आसान रेसिपी", "घर का खाना"],
    ar: ["وصفة سهلة", "طبخ منزلي"],
    fil: ["madaling recipe", "lutong bahay"],
  },
  travel: {
    is: ["ferðavlog", "ódýr ferð"],
    lv: ["ceļojumu vlogs", "lēts ceļojums"],
    lt: ["kelionių vlogas", "pigios kelionės"],
    el: ["travel vlog", "φθηνό ταξίδι"],
    cs: ["cestovní vlog", "levné cestování"],
    hu: ["utazós vlog", "olcsó utazás"],
    ro: ["vlog de călătorie", "vacanță ieftină"],
    uk: ["тревел влог", "бюджетна подорож"],
    id: ["vlog travel", "liburan murah"],
    hi: ["ट्रैवल व्लॉग", "सस्ता सफर"],
    ar: ["فلوج سفر", "سفر رخيص"],
    fil: ["travel vlog", "murang biyahe"],
  },
  fashion: {
    is: ["fatastíll", "notað föt"],
    lv: ["tērpu idejas", "lietoti apģērbi"],
    lt: ["aprangos idėjos", "dėvėti rūbai"],
    el: ["ιδέες ρούχα", "μεταχειρισμένα"],
    cs: ["outfity", "second hand móda"],
    hu: ["outfit ötletek", "túrós ruha"],
    ro: ["idei ținute", "haine second hand"],
    uk: ["образи", "секонд-хенд"],
    id: ["ide outfit", "thrifting"],
    hi: ["आउटफिट आइडिया", "थ्रिफ्ट"],
    ar: ["أفكار لبس", "ملابس مستعملة"],
    fil: ["outfit ideas", "ukay-ukay"],
  },
  parenting: {
    is: ["foreldrar ráð", "fjölskylduvlog"],
    lv: ["vecāku padomi", "ģimenes vlogs"],
    lt: ["tėvystės patarimai", "šeimos vlogas"],
    el: ["συμβουλές γονείς", "οικογενειακό vlog"],
    cs: ["rady pro rodiče", "rodinný vlog"],
    hu: ["szülői tippek", "családi vlog"],
    ro: ["sfaturi părinți", "vlog familie"],
    uk: ["поради батькам", "сімейний влог"],
    id: ["tips parenting", "vlog keluarga"],
    hi: ["पेरेंटिंग टिप्स", "फैमिली व्लॉग"],
    ar: ["نصائح تربية", "فلوج عائلي"],
    fil: ["parenting tips", "family vlog"],
  },
  "personal-finance": {
    is: ["spara peninga", "heimilisbókhald"],
    lv: ["taupīt naudu", "budžets"],
    lt: ["taupyti pinigus", "biudžetas"],
    el: ["εξοικονόμηση", "προϋπολογισμός"],
    cs: ["šetřit peníze", "rozpočet"],
    hu: ["pénzt spórolni", "költségvetés"],
    ro: ["economisește", "buget"],
    uk: ["економія грошей", "бюджет"],
    id: ["hemat uang", "anggaran"],
    hi: ["पैसे बचाओ", "बजट टिप्स"],
    ar: ["توفير المال", "ميزانية"],
    fil: ["magtipid", "budget tips"],
  },
  "diy-home": {
    is: ["gera það sjálfur", "skrifborð"],
    lv: ["pats dari", "darba galds"],
    lt: ["pasidaryk pats", "stalo setup"],
    el: ["φτιάξτο μόνος", "setup γραφείου"],
    cs: ["udělej si sám", "setup stolu"],
    hu: ["csináld magad", "íróasztal setup"],
    ro: ["fă-o singur", "setup birou"],
    uk: ["зроби сам", "сетап столу"],
    id: ["DIY rumah", "setup meja"],
    hi: ["DIY घर", "डेस्क सेटअप"],
    ar: ["اصنعها بنفسك", "ترتيب المكتب"],
    fil: ["DIY sa bahay", "desk setup"],
  },
  pets: {
    is: ["hundamarkþjálfun", "kattarumhirða"],
    lv: ["suņa apmācība", "kaķa kopšana"],
    lt: ["šuns dresūra", "katės priežiūra"],
    el: ["εκπαίδευση σκύλου", "φροντίδα γάτας"],
    cs: ["výcvik psa", "péče o kočku"],
    hu: ["kutyasuli", "macskaápolás"],
    ro: ["dresaj câine", "îngrijire pisică"],
    uk: ["дресирування собаки", "догляд за котом"],
    id: ["latih anjing", "perawatan kucing"],
    hi: ["कुत्ता ट्रेनिंग", "बिल्ली की देखभाल"],
    ar: ["تدريب كلب", "العناية بالقطط"],
    fil: ["pagsasanay ng aso", "alaga ng pusa"],
  },
  "fps-esports": {
    is: ["FPS leikur", "ranked"],
    lv: ["FPS spēle", "ranked"],
    lt: ["FPS žaidimas", "ranked"],
    el: ["FPS gameplay", "ranked"],
    cs: ["FPS hra", "ranked"],
    hu: ["FPS játék", "ranked"],
    ro: ["gameplay FPS", "meci ranked"],
    uk: ["FPS геймплей", "ранкед"],
    id: ["gameplay FPS", "ranked"],
    hi: ["FPS गेमप्ले", "रैंक्ड मैच"],
    ar: ["FPS جيم بلاي", "رانكد"],
    fil: ["FPS gameplay", "ranked match"],
  },
};
